services:
  app1:
    container_name: api01
    image: nmatsui/hello-world-api
    ports:
      - "3000:3000"
    environment:
      - MESSAGE=Piero Cardenas Julian copia 1

  app2:
    container_name: api02
    image: nmatsui/hello-world-api
    ports:
      - "3001:3000"
    environment:
      - MESSAGE=Piero Cardenas Julian copia 2

  app3:
    container_name: api03
    image: nmatsui/hello-world-api
    ports:
      - "3002:3000"
    environment:
      - MESSAGE=Piero Cardenas Julian copia 3

  db:
    image: postgres
    container_name: Lab_2
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=laboratorio02
      - POSTGRES_USER=piero
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: